interface Window {
  api: {
    scanVstPlugins: () => Promise<any[]>;
    getAsioDrivers: () => Promise<any[]>;
    getAsioDriverDetails: (driverName: string) => Promise<{
      name: string;
      inputsCount: number;
      outputsCount: number;
      inputChannels: string[];
      outputChannels: string[];
      minBufferSize: number;
      maxBufferSize: number;
      preferredBufferSize: number;
      bufferSizeGranularity: number;
      inputLatencySamples: number;
      outputLatencySamples: number;
      sampleRate: number;
    } | null>;
    openAsioControlPanel: (driverName: string) => Promise<{ success: boolean }>;
    loadVstPlugin: (path: string) => Promise<any>;
    vstSetSharedBuffer: (instanceId: number, inputSAB: SharedArrayBuffer, outputSAB: SharedArrayBuffer, midiSAB: SharedArrayBuffer) => Promise<{ success: boolean }>;
    vstStartAudio: (instanceId: number, sampleRate: number, blockSize: number) => Promise<{ success: boolean }>;
    vstStopAudio: (instanceId: number) => Promise<{ success: boolean }>;
    getVstParams: (instanceId: number) => Promise<any[]>;
    setVstParam: (instanceId: number, index: number, value: number) => Promise<{ success: boolean }>;
    openVstEditor: (instanceId: number) => Promise<{ success: boolean }>;
    closeVstEditor: (instanceId: number) => Promise<{ success: boolean }>;
    unloadVstPlugin: (instanceId: number) => Promise<{ success: boolean }>;
    onVstEditorClosed: (callback: (instanceId: number) => void) => () => void;
    onVstNativeEditorClosed: (callback: () => void) => () => void;
    readFileBuffer: (path: string) => Promise<any>;
    getHomeDir: () => Promise<string>;
    fileExists: (filePath: string) => Promise<boolean>;
    getSystemPath: (name: string) => Promise<string>;
    saveRecording: (path: string, buffer: ArrayBuffer) => Promise<{ success: boolean; error?: string }>;
    getDiskSpace: (dirPath: string) => Promise<{ success: boolean; freeBytes: number }>;
    getMediaInfo: (path: string) => Promise<{ duration: number; channels?: number; tags?: any }>;
    showSaveDialog: (options: any) => Promise<{ canceled: boolean; filePath?: string }>;
    showOpenDialog: (options: any) => Promise<{ canceled: boolean; filePaths: string[] }>;
    savePreset: (path: string, preset: any) => Promise<{ success: boolean; error?: string }>;
    loadProject: (path: string) => Promise<{ success: boolean; data: any }>;
    saveProject: (path: string, data: any) => Promise<{ success: boolean; error?: string }>;
    saveProjectBackup: (path: string, data: any) => Promise<any>;
    exportArrangement: (path: string, tracks: any[]) => Promise<void>;
    exportLayer: (path: string, track: any) => Promise<void>;
    readDir: (path: string) => Promise<any[]>;
    getSettings: () => Promise<any>;
    saveSettings: (settings: any) => Promise<void>;
    getWaveformData: (path: string) => Promise<any>;
    exportProject: (tracks: any[], path: string, id3Tags?: any) => Promise<boolean>;
    openExternal: (url: string) => Promise<void>;
    getPeaks: (path: string, samples?: number, channel?: 'left' | 'right') => Promise<number[]>;
    openPath: (dirPath: string) => Promise<{ success: boolean; error?: string }>;
    downloadPluginFile: (payload: { url: string; fileName?: string; pluginName?: string }) => Promise<{ success: boolean; error?: string; filePath?: string; directory?: string }>;
    transcodeExport: (tempWavPath: string, outputPath: string, options: any, id3Tags?: any) => Promise<boolean>;
    getStartupFile: () => Promise<string | null>;
    onOpenProjectFromAssociation: (callback: (filePath: string) => void) => () => void;
    onCloseRequest: (callback: () => void) => () => void;
    confirmClose: () => void;
    checkForUpdates: () => Promise<{
      available: boolean;
      currentVersion: string;
      latestVersion?: string;
      url?: string;
      body?: string;
      error?: string;
    }>;
    getAppVersion: () => Promise<string>;
    startUpdateDownload: (payload: { url: string; latestVersion: string }) => Promise<{ success: boolean; error?: string; filePath?: string }>;
    cancelUpdateDownload: () => Promise<{ success: boolean }>;
    installUpdate: (payload: { installNow: boolean }) => Promise<{ success: boolean; error?: string; deferred?: boolean }>;
    readChangelog: () => Promise<string>;
    onDownloadProgress: (callback: (data: any) => void) => () => void;
    getPerformanceStats: () => Promise<{ cpuUsage: number, processRamBytes: number, systemRamPct: number, systemCpuPct: number }>;
    getLocales: () => Promise<any>;
    saveLocale: (lang: string, content: any) => Promise<{ success: boolean; error?: string }>;
    openExportSettings: (tracks: any, selection?: any, exportSettings?: any) => void;
    getExportTracks: () => Promise<{ tracks: any[]; selection: any; exportSettings: any } | null>;
    updateExportSettings: (settings: any) => void;
    startOfflineExport: (settings: any) => void;
    updateExportProgress: (progress: number, label: string) => void;
    notifyExportFinished: (status: string, filePath?: string, errorMsg?: string) => void;
    closeProgressWindow: () => void;
    seekTimeline: (position: number) => void;
    onExportSettingsUpdated: (callback: (settings: any) => void) => () => void;
    onStartOfflineRender: (callback: (settings: any) => void) => () => void;
    onExportProgressUpdate: (callback: (data: { progress: number; label: string }) => void) => () => void;
    onExportFinished: (callback: (data: { status: string; filePath?: string; errorMsg?: string }) => void) => () => void;
    onLockMainWindow: (callback: (locked: boolean) => void) => () => void;
    onSeekTimeline: (callback: (position: number) => void) => () => void;
    openPopoutWindow: (name: string, options?: { width?: number; height?: number; title?: string }) => void;
    resizeWindow: (width: number, height: number) => void;
  };
}

declare module "*.png" {
  const value: string;
  export default value;
}

declare module 'ffprobe-static';
